### ISSUE TITLE
No support for metadata in rockspecs

### ISSUE THREAD

**Issue by agladysh** [keplerproject/luarocks#19]
I need to be able to put "x-something" fields anywhere in the tree.

**Comment by raingloom** [comment]
I was bitten by this exact same issue, because I wanted to add a tag that is not YET supported (`issues_url`) and luarocks gave me a hard error without any indication that I can just use a flag to force it through.

Honestly, this should have never been a hard error, not even when building. A warning would be fine, but there is really no reason to throw a hard error when the format is not actually wrong.

**Comment by hishamhm** [comment]
> when the format is not actually wrong.

When adding unknown fields to a file, the format _is_ wrong. You wouldn't add random bytes to a JPEG header and expect it to work.

**Comment by raingloom** [comment]
PNG supports arbitrary chunks, that's what enabled PICO-8 to work as amazingly as it does. So no, the format should only care about what it will touch and not error unless there is a problem with those.
If people wanted static checking all over the place, they would not use Lua.

**Comment by raingloom** [comment]
And as I said, I was not using anything that would trip up anything, I was using a documented feature that's not yet supported. If I exported `DISPLAY` even though I wasn't running in an X session, should the shell error?
