### ISSUE TITLE
Variables assignments for build type "make" hard-override existing Makefile variables

### ISSUE THREAD

**Issue by vsergeev** [keplerproject/luarocks#300]
When building a rockspec that uses build type "make" and specifies a number of build environment variables, e.g.:

```
...
build = {
    type = "make",
    variables = {
        CFLAGS = "-Ifoo",
        LUA_LIBDIR = "$(LIBDIR)",
        LUA_SHAREDIR = "$(LUADIR)",
    },
    copy_directories = { "docs" },
}
```

LuaRocks will call `make` on the sources with an invocation (https://github.com/keplerproject/luarocks/blob/v2.2.0/src/luarocks/build/make.lua#L32) like
```
make <target> CFLAGS=-Ifoo/ LUA_LIBDIR=$(LIBDIR) LUA_SHAREDIR=$(LUADIR)
```

Rather than
```
CFLAGS=-Ifoo/ LUA_LIBDIR=<baz> LUA_SHAREDIR=<bar> make <target>
```

Passing these variables as arguments to `make` (the former), rather than setting them in the environment for the `make` process (the latter), causes `make` to hard-override these variables, so the Makefile can't modify or append to them with a line like `CFLAGS += -Wall`, unless it uses the `override` specifier. However, the latter approach is different in that it can't carry `make` variable assignments like `$(LIBDIR)` or `make` built-in functions.

This is a problem in cases where build environments (like buildroot) may need to pass additional flags important to the target (e.g. `-mfpu=`) in a variable that the rockspec also modifies (e.g. `CFLAGS`) and the Makefile supplements. In most other cases, any modification of a build variable in the rockspec must carry all the other intended additional settings of that variable from the Makefile and consequently tightly couples the rockspec to the Makefile.

**Comment by hishamhm** [comment]
Just to complement, I agree with @siffiejoe that this is unlikely to change since we depend on this behavior and users have come to expect that whatever they put in the rockspec and in their config.lua file is what will be used during build.

The rockspec is tightly coupled to the Makefile, indeed. A rockspec setting CFLAGS should propagate "$(CFLAGS)" (the value that comes from the user's configuration), so that for instance, buildroot may set `-mfpu=` in its config.lua file and have it applied to every rockspec.
