### ISSUE TITLE
Builtin build copies more than maybe it should?

### ISSUE THREAD

**Issue by geoffleyland** [keplerproject/luarocks#321]
As shown below, an empty builtin build will copy everything in a directory named "lua".  Is this intended behaviour?

    $ luarocks --version
    /usr/local/bin/luarocks scm
    LuaRocks main command-line interface

    $ mkdir luarocks-test
    $ cd luarocks-test/
    $ luarocks write_rockspec test 1 .
    Warning: Please specify supported Lua version with --lua-version=<ver>. See '/usr/local/bin/luarocks help write_rockspec'.

    Wrote template at ~/luarocks-test/test-1-1.rockspec -- you should now edit and finish it.

    $ mkdir lua
    $ touch lua/dont_copy_me.txt
    $ sudo luarocks make
    Updating manifest for /usr/local/lib/luarocks/rocks
    test 1-1 is now built and installed in /usr/local (license: *** please specify a license ***)

    $ ls /usr/local/share/lua/5.1/dont*
    /usr/local/share/lua/5.1/dont_copy_me.txt

**Comment by hishamhm** [comment]
Well... yeahhh, I guess.

I mean, I added this feature as a way to avoid having to list every `.lua` module in a builtin build, as a sort of convention. I ended up never advertising this feature much, so I don't even know if any rockspec out there uses it (but who knows what goes on in private repositories; can't take out the feature by now). In any case, restricting it to, say, `.lua` file extensions could be problematic since I've seen people installing other things into LUADIR on purpose (MoonScript `.moon` and TypedLua `.tld` files, for example).

**Comment by geoffleyland** [comment]
As you wish.  I was using `luarocks make` on some local projects and was just surprised to find all the junk I'd left in the `lua` directory copied.  As long as it's expected, that's fine.  Maybe document it?  I s'pose I could edit the wiki?

**Comment by geoffleyland** [comment]
...or maybe an option to builtin to say there's no default copying?

**Comment by hishamhm** [comment]
Adding an option now would make the rockspec break in older versions of LuaRocks, but it's something that could be changed in the future. For now documenting would be best (and yes, it would help a lot if you edited the wiki! Thank you!!)

**Comment by geoffleyland** [comment]
Done!

**Comment by hishamhm** [comment]
Thank you!! :)
