### ISSUE TITLE
lsqlite3 rock install failed using luarocks 2.2

### ISSUE THREAD

**Issue by ivopivo** [keplerproject/luarocks#377]
I compiled and installed Lua 5.3 from sources on Windows using mingw
Then I installed luarocks 2.2.0
Tried to install luasocket using
``` luarocks install luasocket```
and everything works fine, I can use socket module in my scripts, but when I tried to install 
```luarocks install lsqlite3 ```
I'm still getting the following error. What I'm missing? 
What is  ```-Lc:/external/lib``` switch?

```
c:\temp\luarocks>luarocks install lsqlite3 SQLITE_INCDIR=c:\temp\sqlitesrc
Installing https://luarocks.org/lsqlite3-0.9.3-0.src.rock...
Using https://luarocks.org/lsqlite3-0.9.3-0.src.rock... switching to 'build' mode
mingw32-gcc -O2 -c -o lsqlite3.o -Ic:/dev/lua/include lsqlite3.c -DLSQLITE_VERSION="0.9.3" -Ic:\temp\sqlitesrc
mingw32-gcc -shared -o lsqlite3.dll lsqlite3.o -Lc:/external/lib -lsqlite3 c:/dev/lua/lib/lua53.dll -lm
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lsqlite3
collect2.exe: error: ld returned 1 exit status
```

Whole process output is here:
https://gist.github.com/ivopivo/2c2671301b546c94693f

UPDATE:

I downloaded precompiled sqlite3.dll from sqlite website adding it to c:\external\lib and after that
compilation works as follows

```
C:\WINDOWS\system32>luarocks install lsqlite3 SQLITE_INCDIR=c:\temp\sqlitesrc
Installing https://luarocks.org/lsqlite3-0.9.3-0.src.rock...
Using https://luarocks.org/lsqlite3-0.9.3-0.src.rock... switching to 'build' mode
mingw32-gcc -O2 -c -o lsqlite3.o -Ic:/dev/lua/include lsqlite3.c -DLSQLITE_VERSION="0.9.3" -Ic:\temp\sqlitesrc
mingw32-gcc -shared -o lsqlite3.dll lsqlite3.o -Lc:/external/lib -lsqlite3 c:/dev/lua/lib/lua53.dll -lm
Updating manifest for c:\dev\luarocks\systree/lib/luarocks/rocks
lsqlite3 0.9.3-0 is now built and installed in c:\dev\luarocks\systree (license: MIT/X11)
```

**but when I try to use module I'm getting error:**

```
C:\WINDOWS\system32>lua -l lsqlite3
lua: error loading module 'lsqlite3' from file 'c:\dev\lua\bin\lsqlite3.dll':
        The specified module could not be found.
```

It looks like lua find lsqlite3.dll .. I put it into c:\dev\lua\bin directory which is in my package.path ... but even so can't load module from it.

Thanks, I.

**Comment by siffiejoe** [comment]
> What is -Lc:/external/lib switch?

That switch tells `gcc` to look for library files in `c:\external\lib`. Sadly, there is no default directory on Windows where include files or libraries are installed, so `c:\external\lib` is just the default LuaRocks uses on Windows. You can change that in the config file: `external_deps_dirs = { "c:\otherdir" }` (the `lib` is appended automatically because of the `external_deps_subdirs` config variable).

> It looks like lua find lsqlite3.dll .. I put it into c:\dev\lua\bin directory which is in my package.path ... but even so can't load module from it.

`lsqlite3.dll` is a C module, so the relevant variable is `package.cpath`. But `package.cpath` by default includes the directory of the Lua executable, so that's not the problem. My guess is that the `sqlite3.dll` (the one without the "l" at the beginning) is not found at runtime. Copy it from the `c:\external\lib` directory to `c:\dev\lua\bin` (or any directory in your `PATH`).

**Comment by ivopivo** [comment]
:) copying sqlite3.dll to the path helped. Thanky you very much Philipp!
