### ISSUE TITLE
cmake build does not generate 64 bit build for windows.

### ISSUE THREAD

**Issue by xpol** [keplerproject/luarocks#382]
cmake build does not generate 64 bit build for windows when luarocks installed with a 64 bit lua.

**Comment by ignacio** [comment]
We need to add  `-DCMAKE_GENERATOR_PLATFORM=x64` to the command line.
I wonder why CMake does not do that by default.

**Comment by ignacio** [comment]
@xpol could you try the fix I submitted [here](https://github.com/keplerproject/luarocks/pull/383) ?

**Comment by ignacio** [comment]
Meh, I'm not happy with this. To be able to use `CMAKE_GENERATOR_PLATFORM=x64` we need to know if we're on Windows, using MSVC and Lua has been built as 64 bits.
When using makefiles, the above does not apply. I also don't know what happens when using Mingw.

Right now, I'm looking for a way to get cmake to report which compiler is going to use.

**Comment by xpol** [comment]
I'm back here again.
Today i tried the 64 bit build for lua-rapidjson.


But it seems have issue when install busted.
Every depended module has no install error but it still reports the missing depends.

See my build log here on [appveyor](https://ci.appveyor.com/project/xpol/lua-rapidjson/build/job/co8xsoibniia73xn).

I don't know exactly is this due to luarocks or busted or just my [install_lua.bat](https://github.com/xpol/lua-rapidjson/blob/master/.scripts/install_lua.bat) has gone wrong.

**Comment by ignacio** [comment]
This may not be a LuaRocks issue. It is CMake that it is using a newer Visual Studio version instead of the one you chose in appveyor. You need to choose the generator when building, and you should do that in your `config.lua`, by setting `cmake_generator` to the appropiate value.
This might be a nice addition to https://github.com/ignacio/lua-appveyor-example

I'm testing a fix for that.
