### ISSUE TITLE
Adding an additional path for modules

### ISSUE THREAD

**Issue by thefosk** [keplerproject/luarocks#411]
I am using OpenResty and I would like to add an additional include path to LuaRocks, to lookup for modules in the `/usr/local/openresty/lualib/` folder (besides the default locations). 

Right now I am getting the following error, because of course that path is not included:

```
module 'resty.lrucache' not found:No LuaRocks module found for resty.lrucache
```

What is the best practice for doing this?

#### Update:

Currently I fixed this manually editing the `/usr/local/bin/luarocks` file by changing this line:

```
package.path = [[/usr/local/share/lua/5.1/?.lua;/usr/local/openresty/lualib/?.lua;]]..package.path
```

But I am pretty sure there must be a better way, maybe during the installation of LuaRocks. The config I am currently exporting is:

```lua
rocks_trees = {
   { name = [[system]], root = [[/usr/local]] }
}
```

**Comment by ignacio** [comment]
Have you tried setting LUA_PATH and LUA_CPATH ?

**Comment by hishamhm** [comment]
This is an issue between OpenResty and your Lua configuration, not your LuaRocks configuration.

You're getting the `"No LuaRocks module found for"` from the LuaRocks package loader, which is probably being loaded by OpenResty. But this is only one of the package loaders. Lua installs two other loaders by default: one to load `.lua` modules and another to load `.so` modules.

If `/usr/local/openresty/lualib/` contains modules that are not installed via LuaRocks, then they should be loaded by the standard Lua package loader. The standard `.lua` loader uses the value of `package.path` (that's why your tweak worked) — but `package.path` is set initially by loading `LUA_PATH` (as mentioned by @ignacio). For `.so` modules, `package.cpath` is used, populated via `LUA_CPATH`.

The easiest solution is to set `LUA_PATH` and `LUA_CPATH` in your environment. This is beyond the scope of LuaRocks.
