### ISSUE TITLE
Registering via GitHub

### ISSUE THREAD

**Issue by deathbeam** [keplerproject/luarocks#415]
I think this would be good addition as most of rocks are anyway located on GitHub. So adding button to LuaRocks register page that will let register you with your GitHub account makes sense.

**Comment by hishamhm** [comment]
Hi!

You can already link your LuaRocks account to your GitHub account. This makes it easy to claim any projects in the repository which are hosted in GitHub.

I'm closing this one since this is a bug tracker for the LuaRocks tool and not the website (which is at https://github.com/leafo/luarocks-site — you might want to post any website issues there). But thanks for the feedback!

**Comment by deathbeam** [comment]
Yes, but I do not meant that. Okay then I will repostthis issue there.
