### ISSUE TITLE
Use behind a proxy server

### ISSUE THREAD

**Issue by aseempatni** [keplerproject/luarocks#419]
How can I use luarocks behind a proxy?

```
$ luarocks install loadcaffe
Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
Cloning into 'loadcaffe'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection refused


Error: Failed cloning git repository.
```
i tried adding `proxy="http://ip:port/"` in `config.lua` but still not working.
wget and git clone are normally working fine.
`http_proxy` and `https_proxy` are also set properly.

**Comment by ignacio** [comment]
Hi! While LuaRocks now supports working behind a proxy, it hasn't been released yet. See #337

**Comment by shubh-agrawal** [comment]
Do enter this command in terminal,
git config --global url."https://".insteadOf git://
since you have got http and https proxies, it wont allow protocols like git, imap, smtp to pass through. 
With above git configuration, git will always use http protocol to clone packages.
Comment if something goes wrong even with this

**Comment by fengyuleidian0615** [comment]
@shubh-agrawal 
Indeed, the url in the spec file is git protocol, so unless git proxy is properly configured, 

> git config --global url."https://".insteadOf git://
is needed, and it helps on my env.
Thanks!
