### ISSUE TITLE
Luarocks uses clang by default, how do I change it to GCC?

### ISSUE THREAD

**Issue by metatl** [keplerproject/luarocks#445]
Hi, 
My xcode version is not high enough to completely support C++11, which is needed to install a package. I brewed a gcc compiler on the system. However, luarocks recognizes that the default compiler is clang.
Is there a way to change that?

I am running 10.8 Mac. 

Thanks!

**Comment by daurnimator** [comment]
You can pass `CC=gcc` to luarocks. e.g. `luarocks install somelibrary CC=gcc`.
You can make this change permanent by editing your luarocks config, which will be located somewhere like: `/usr/share/lua/5.3/luarocks/site_config.lua`

**Comment by hishamhm** [comment]
Try `luarocks build your_package CC="/path/to/your/gcc"
LD="/path/to/your/gcc"`

**Comment by metatl** [comment]
@hishamhm @daurnimator 
Thanks guys. However, I realized that it's a slightly different issue. The package I want to install uses cmake and cmake has its default compilers. Can I change those temporarily through luarocks too?

**Comment by daurnimator** [comment]
> Thanks guys. However, I realized that it's a slightly different issue. The package I want to install uses cmake and cmake has its default compilers. Can I change those temporarily through luarocks too?

It will be passed through to cmake as `-D CC=gcc`.

**Comment by metatl** [comment]
@daurnimator 
thanks. I just solved the issue by export CC=gcc-4.8
This is more superficial but worked this time. 
Is your way more guaranteed?

**Comment by kirk86** [comment]
@daurnimator What is the proper syntax to permanently add that change to `site_config.lua`

is it `site_config.CC=[[/path/to/compiler]]`
or `site_config.LUA_CC=[[/path/to/compiler]]`
or maybe `site_config.LUAROCKS_CC=[[/path/to/compiler]]`

**Comment by daurnimator** [comment]
Actually I think it goes in config.lua.
e.g.   /etc/luarocks/config-5.1.lua 

```
variables = {
	CFLAGS="-O2 -fPIC";
	CC="gcc";
	LD="gcc";
}
```

**Comment by kirk86** [comment]
@daurnimator Thanks a lot. I'm gonna try it and if things work fine I'll close this issue.

By the way since we are on the topic of compilers can I ask a question in case that you might know something more than me.

I've been trying to install the torch package which is mainly lua and lots of c code.

I have in my system (OS X) a number of different compilers (clang[no openmp support], clang[openmp support], gcc, and intel-mkl compilers).

I can compile the library with the clang compilers but not with gcc and intel compilers even though the library is compatible with those compilers.

What's even stranger is that for instance I can compile and install the library via clang and then install different rocks via luarocks by explicitly telling it to use intel-mkl compilers.

Any thoughts?

**Comment by daurnimator** [comment]
which bit didn't work?

**Comment by kirk86** [comment]
what i did was the following based on your suggestion
`variables = {`
        `CC=/usr/local/bin/icc`
        `CXX=/usr/loca/bin/icpc`
`}`

but it didn't work.

If I set them up via shell with `export CC=...` then it works. So when I install something with luarocks I can see that it uses the write compiler.

**Comment by daurnimator** [comment]
did you use quotes (`"`")?

**Comment by kirk86** [comment]
yes of course `"` quotes and semicolons `;` but no luck

**Comment by Hydroque** [comment]
The answer is in variables table.
variables = {
	CC = "gcc";
	LD = "gcc";
}
for example
