### ISSUE TITLE
keplerproject.org dead

### ISSUE THREAD

**Issue by lordnynex** [keplerproject/luarocks#458]
Hello,

Sorry, this issue is not to do with luarocks. For almost  a week now I have not been able to reach keplerproject.org. This, unfortunately, is causing problems with other websites. In particular, a LOT of projects link keplerproject.org/doc.css in their user documentation. This causes pages to not load or hang for a very long time. This has a pretty large impact on such a small community. Is there anything I can do to help fix this? Can I offer hosting for the domain? Can we get a rewrite rule on doc.css to a cdn copy?

**Comment by ignacio** [comment]
Some modules had been fixed a long time ago. Could you email me a list of the modules which has this issue? I can submit PRs for them. (email address should appear in my profile).

I don't think hosting keplerproject.org is worth it. Most modules these days had been updated to use local links to css files and also to use github pages to host the docs.

I'll close this now, since it's not LR related, but send me that module list.
