### ISSUE TITLE
Handling of cfg.local_cache = nil

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/luarocks#479]
Not an issue really, just a question: there is [some code](https://github.com/keplerproject/luarocks/blob/878f56e1f05447cfe1c79ef9b720433b51e61bd9/src/luarocks/cache.lua#L61-L66) in `luarocks.cache.refresh_local_cache` that tries to handle the case when `cfg.local_cache` is not set (it creates a temporary cache directory, but that moment is not reached because of a previous `fs.make_dir(cfg.local_cache)` call). Is this a broken feature that should be fixed or just dead code?

**Comment by hishamhm** [comment]
It looks like a bit of both:

https://github.com/keplerproject/luarocks/commit/772410c041f3fa9480e49e7aea88ec265a74b89d#diff-03068231cca3e504d4be4673f90660a3L56

It's a broken feature because before this diff `fs.make_dir` failed silently which led to the `fs.make_tmp_dir` block, so supposedly it did execute.

But it also seems like unfinished/dead code because there's a `tmp_cache` flag there that's not used anywhere else.

Well, since nobody complained about this since 2013, perhaps it's fair to call it dead code and get rid of it? In practice, `cfg.local_cache` is always set by the `defaults` in `luarocks.cfg`.
