### ISSUE TITLE
Fix & update Luarocks documentation

### ISSUE THREAD

**Issue by MisterDA** [keplerproject/luarocks#486]
On the [Development](https://github.com/keplerproject/luarocks/wiki/Development) page there's a link to a [generated documentation](http://luarocks.luaforge.net/luadoc/) which happens to be outdated and far from complete. Some functions in Luarocks are not documented, while some documented functions don't exist anymore in Luarocks.
A call to `ldoc .` gives me a bunch of errors and won't generate anything.
I assume most of you are very familiar with the architecture and the functions Luarocks provide, but it's good to keep the docs synced. If there's too much to fix, you could at least add a note explaining the documentation is outdated.
I wanted to use `luarocks.fs` for a side project and I found myself crawling through the sources rather than simply reading a webpage.

**Comment by mpeterv** [comment]
As I understand it you shouldn't use luarocks modules in other projects because the interface is not stable.

**Comment by mpeterv** [comment]
I've added a small note to the wiki page. @hishamhm we could fix the docs and host them on http://keplerproject.github.io/luarocks/ somewhere. ldoc warnings are easily fixable, most of them are because of deps_mode argument that's not documented almost anywhere.

**Comment by mpeterv** [comment]
@hishamhm do we plan to support anybody using luarocks internals in LR3? I'd rather not, in which case generating even internal docs could give a wrong idea. Having a very high level public interface would be nice though.

**Comment by hishamhm** [comment]
> do we plan to support anybody using luarocks internals in LR3?

Not in LR 3.0 at least. LR modules are too stateful (very dependent on stuff set via `cfg` such as `--tree`), this would have to be cleaned up in order to present a public API and I don't see this all changing any time soon.

I could consider spinning off `luarocks.fs` as a stand-alone module if that was deemed generally useful, but I'm worried if that would give us more development overhead than community contributions from a wider usage would save.

In any case, I removed the link from the wiki page, which is a spartan but realistic solution to this issue.
