### ISSUE TITLE
Warning: Failed loading manifest for /home/werner/.luarocks/lib/luarocks/rocks: /home/werner/.luarocks/lib/luarocks/rocks/manifest: No such file or directory

### ISSUE THREAD

**Issue by hongyi-zhao** [keplerproject/luarocks#535]
Hi all,

When I run the ``luarocks list'', I meet the following warning:

werner@debian-01:~$ luarocks list
Warning: Failed loading manifest for /home/werner/.luarocks/lib/luarocks/rocks: /home/werner/.luarocks/lib/luarocks/rocks/manifest: No such file or directory

Installed rocks:
----------------

luafilesystem
   1.6.3-2 (installed) - /usr/local/lib/luarocks/rocks

luaposix
   33.4.0-1 (installed) - /usr/local/lib/luarocks/rocks

luarocks
   2.3.0-1 (installed) - /usr/local/lib/luarocks/rocks

luasocket
   3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks

**Comment by robooo** [comment]
I think it's OK because after every manifest search it checks for errors and print warning message
```
      if not ok then
         util.warning(err)
      end
```
so first find local or remote manifest, then installed rocks, but I could be wrong

**Comment by hongyi-zhao** [comment]
[1]  How to suppress this waring or make the manifest?
[2]  Even this warning exists for my case, it doesn't effect the installation of any modules, so it's harmless, am I right?

Regards

**Comment by hishamhm** [comment]
@robooo That's correct. Looking back, I think it would be nicer if we supressed the error in the "file not found" case (because that always happens when the user first installs LuaRocks and `~/.luarocks` doesn't exist yet), but it would be good to report on any other errors (such as a corrupted manifest). We'd probably need a third return result (`nil, err, errcode`) so we could test something like `if errcode == "missing"` and not depend on the string of the message.

@hongyi-zhao 
[1]:

```
mkdir -p ~/.luarocks/lib/luarocks/rocks
bin/luarocks-admin make-manifest --local-tree --tree=$HOME/.luarocks
```

[2] Yes, it's hamless!
