### ISSUE TITLE
build fails when make works

### ISSUE THREAD

**Issue by vadi2** [keplerproject/luarocks#539]
To my understanding, both commands should work the same, but they aren't.

```
vadi@gooseberry:~/Programs/fhir-formats-(git/ master )$ sudo luarocks build fhir-formats-0.1.0-1.rockspec 

Error: Build error: Failed installing src/fhir-formats.lua in /usr/local/lib/luarocks/rocks/fhir-formats/0.1.0-1/lua/fhir-formats.lua
vadi@gooseberry:~/Programs/fhir-formats-(git/ master )$ sudo luarocks make
Updating manifest for /usr/local/lib/luarocks/rocks
fhir-formats 0.1.0-1 is now built and installed in /usr/local (license: Apache License 2.0)

vadi@gooseberry:~/Programs/fhir-formats-(git/ master )$ 
```

```
$ luarocks --version
/usr/local/bin/luarocks 2.3.0
LuaRocks main command-line interface
```

**Comment by mpeterv** [comment]
The difference between `make` and `build` is that `build` fetches sources while `make` uses whatever is in local directory. In your case `build` fails because URL is the rockspec is incorrect, it should use git:// protocal instead of https://. (fetching from github using https:// returns home page of your project, which isn't very useful.)

**Comment by vadi2** [comment]
I thought it only fetched dependencies, not the source itself as well - thanks! The error out to mention it failed to obtain the source.
