### ISSUE TITLE
Update your Windows Tools

### ISSUE THREAD

**Issue by Stanzilla** [keplerproject/luarocks#589]
Stuff like 7zip is outdated and very vulnerable http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html

**Comment by siffiejoe** [comment]
See also #565.

**Comment by Stanzilla** [comment]
Oh sorry, guess I missed that. Is this project still actively maintained btw? Or only on life support, accepting PRs etc?

**Comment by hishamhm** [comment]
@Stanzilla by this you mean LuaRocks or Lua for Windows? LuaRocks is actively maintained. Lua for Windows, I'm not sure, but it hasn't had a release for a long time.

**Comment by Stanzilla** [comment]
Well, both a bit. Since LuaRocks uses Lua for Windows it's kinda problematic, I guess?

**Comment by hishamhm** [comment]
you can certainly use LuaRocks without Lua for Windows. But we could certainly use more help for the Windows maintenance part!

**Comment by Stanzilla** [comment]
@hishamhm ok well what's the source for the tools used here? https://github.com/keplerproject/luarocks/tree/master/win32/tools msys?

**Comment by hishamhm** [comment]
@Stanzilla as far as I remember, we got them from here: http://unxutils.sourceforge.net/

**Comment by Stanzilla** [comment]
Oh god. Last release in 2003.

**Comment by hishamhm** [comment]
Better sources to find stand-alone Windows executables for the required programs (with no additional dependencies) are most welcome!

The full story though is that adding these binaries was originally intended as a stop-gap solution until we had a LfW(-like?) package that bundled all the necessary Lua C modules to make LuaRocks work. Then two things happened:

1. The Windows filesystem semantics means that the way we implemented upgrades on Unix doesn't really work on Windows (e.g.: upgrading lfs means removing lfs and installing another copy, but then once lfs is loaded by LuaRocks the file lfs.dll is locked and can't be replaced)
2. The stop-gap solution worked well enough so that nobody bothered to investigate other solutions.

Still, it would be great to move away from depending on these binaries.

**Comment by Stanzilla** [comment]
Well I can't help with that, no experience. But I can do a PR with slightly updated binaries coming from the https://github.com/bmatzelle/gow project. Would that be welcome?

**Comment by hishamhm** [comment]
@Stanzilla yes! the binaries from this link are from 2014, so, while they're probably not exactly up-to-date, it's a great improvement to our current Windows state :)

**Comment by hishamhm** [comment]
Is there an updated 7zip binary (linked to MSVCRT) anywhere?

**Comment by Stanzilla** [comment]
https://github.com/keplerproject/luarocks/pull/591
