### ISSUE TITLE
Install all packages contained in a manifest

### ISSUE THREAD

**Issue by antagon** [keplerproject/luarocks#600]
It would be nice to have a possibility to install all packages contained in a manifest. A package name could be specified as a Lua pattern (as used by _string_ library), all packages matching a pattern would get installed. I take it that manifest files are cached locally so it should not cause any problems to 'rock' servers, as the pattern matching could be performed without additional network requests.

`luarocks install --server=http://luarocks.org/m/luajit "lua-resty-[%g]+"`

This feature would help to deploy script bundles to end-users, without having to package everything into one rock, or having to install each module manually.

**Comment by mpeterv** [comment]
It's definitely a bad idea to make `install` accept Lua patterns as many rock names contain dash, which is a special pattern character (for instance, your example pattern `"lua-resty-[%g]+"` does not actually match something like `"lua-resty-string"`, but matches `"luresty"`.

As for this usecase, IMO installing by pattern is not very good because you can accidentally install something you don't want, simply because someone else happens to have a package matching the pattern. Perhaps it would be better to be able to explicitly list packages to install on the command line or using a requirements file, see #266.

**Comment by antagon** [comment]
That is a valid point. I did not realize that dash is a special character in Lua patterns. Anyway, thank you pointing out a requirements file.
